const fs = require('fs');
const path = require('path');

function walk(dir) {
  let results = [];
  const list = fs.readdirSync(dir);
  list.forEach(file => {
    file = path.join(dir, file);
    const stat = fs.statSync(file);
    if (stat && stat.isDirectory()) {
      results = results.concat(walk(file));
    } else {
      if (file.endsWith('.tsx') || file.endsWith('.ts')) {
        results.push(file);
      }
    }
  });
  return results;
}

const files = walk(path.join(__dirname, 'src'));

files.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');
  let original = content;

  // Improve font sizes and weights
  content = content.replace(/font-black/g, 'font-bold');
  
  // Remove aggressive uppercase and tracking from typical text classes
  // e.g. uppercase tracking-tight -> tracking-tight
  content = content.replace(/uppercase tracking-tighter/g, 'tracking-tight');
  content = content.replace(/uppercase tracking-tight/g, 'tracking-tight');
  content = content.replace(/uppercase tracking-wider/g, 'tracking-normal');
  content = content.replace(/uppercase tracking-widest/g, 'tracking-normal');
  content = content.replace(/ tracking-wider uppercase/g, '');
  content = content.replace(/ tracking-widest uppercase/g, '');
  content = content.replace(/ uppercase/g, ''); // Be careful with this, maybe just uppercase in classNames

  // A safer regex for uppercase in classNames
  // We want to remove 'uppercase' from className strings
  // but we already did some specific ones above. 
  // Let's do a more targeted replace for any remaining standalone 'uppercase' in classNames
  content = content.replace(/className="([^"]*)uppercase([^"]*)"/g, 'className="$1$2"');
  content = content.replace(/className=\{`([^`]*?)uppercase([^`]*?)`\}/g, 'className={`$1$2`}');

  // Improve coloring for secondary text (softer grays instead of pure black with opacity)
  content = content.replace(/text-themeBlack\/60/g, 'text-gray-500');
  content = content.replace(/text-themeBlack\/70/g, 'text-gray-600');
  content = content.replace(/text-themeBlack\/80/g, 'text-gray-700');

  // Let's clean up any double spaces generated by removing words
  content = content.replace(/  +/g, ' ');

  if (content !== original) {
    fs.writeFileSync(file, content, 'utf8');
    console.log('Updated typography in:', file);
  }
});
