export { api, ApiError, onAuthEvent } from './client';
export { API_BASE_URL, TOKEN_STORAGE_KEY, USER_STORAGE_KEY } from './config';
export { authApi } from './auth';
export { patientsApi } from './patients';
export { vitalsApi } from './vitals';
export { medicationsApi } from './medications';
export { testResultsApi } from './testResults';
export { medicalConditionsApi } from './medicalConditions';
export { appointmentsApi } from './appointments';
export type { AppointmentsQuery } from './appointments';
export { dashboardApi } from './dashboard';
export { reportsApi } from './reports';
export { auditLogsApi } from './auditLogs';
export type { AuditLog, AuditLogsQuery } from './auditLogs';
